#include <iostream>
#include <time.h>
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/xfeatures2d.hpp"
#include "ImageContainer.h"
#include "Utility.h"
#include "Epipolar.h"
#include "FileOutput.h"
#include "Feature.h"
#include "Filter.h"
#include "Track.h"
#include "Dense.h"
#include "GCApplication.h"
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
//#include <pcl/registration/icp.h>
#include <pcl/kdtree/kdtree_flann.h>
#include <pcl/features/normal_3d.h>
#include <pcl/surface/gp3.h>
#include <pcl/filters/radius_outlier_removal.h>
#include <pcl/io/vtk_io.h>
#include "BundAdj.h"